### ISSUE TITLE
Suggestion: use a single repository for the visibility script

### ISSUE THREAD

**Issue by waldyrious** [UseAllFive/true-visibility#1]
First of all: I like the concept, and the fact that this doesn't require any libs.

I think it would be nicer if the repo was actually named after the visibility script and contained only that. That would make it more findable (in both Github search and Google) and encourage interested people to fork and contribute. After all, it's unlikely that others will need the exact same set of js utils that you might eventually end up building if this repo expands.

**Comment by jasonfarrell** [comment]
Great idea, I agree. Closed by a173d6a3c84ad9c06dbbcfa6c8f17b95daef5d3d
